
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - RAILS_ENV=development
    command: bash -c "bundle install && rails db:migrate && rails s -b 0.0.0.0"

  frontend:
    build: ./calculator
    ports:
      - "5173:5173"
    volumes:
      - ./calculator:/app
    command: sh -c "npm install && npm run dev"
